/*************************************************************
 *  CALMA HOTEL — Direct Website Booking Backend
 *  -----------------------------------------------------------
 *  What this script does, every single time a guest submits
 *  a form on calmacairohotel.com (either the dedicated Reservation
 *  page at /rc/, or the general Contact page) :
 *
 *   1) Adds ONE new row to a single, permanent Google Sheet
 *      ("Bookings") — every booking/enquiry ever made through the
 *      website lands in that same sheet, never a new one.
 *   2) Uses the booking code the guest already saw on screen
 *      (an "RC-######-####" code generated by the /rc/ page) so the
 *      code on the guest's screen, the code in the sheet, and the
 *      code on both PDFs always match. If a submission doesn't
 *      carry one (e.g. the general Contact form), the sheet
 *      generates its own "CLM-00001" style code instead.
 *   3) Builds a "Reservation Card" (RC) PDF — the guest's full
 *      reservation summary (room, dates, nights, price, guest
 *      details) with a "Digitally Verified" signature stamp —
 *      and saves it to Google Drive.
 *   4) Builds a "Gold Card" PDF — name, code, stay details and a
 *      15% voucher for the guest's next stay — and saves it too.
 *   5) Puts clickable links to both PDFs in the sheet, right next
 *      to the code, so opening either is one click.
 *   6) Emails hatemahmedsayedss2233@gmail.com a summary of the
 *      new booking with both PDF links included.
 *
 *  SETUP: see "دليل التركيب.md" / SETUP_GUIDE.md that came
 *  with this file — you only need to copy/paste this file once.
 *************************************************************/

// ---------------------- CONFIG ----------------------
var OWNER_EMAIL   = 'hatemahmedsayedss2233@gmail.com';
var SHEET_NAME    = 'Bookings';
var DRIVE_FOLDER  = 'CALMA Gold Cards';
var RC_FOLDER     = 'CALMA Reservation Cards';
var HOTEL_NAME    = 'CALMA Hotel';
var HOTEL_PHONE   = '+20 12 7373 6667';
var VOUCHER_PCT   = '15%';
var CURRENCY      = 'EGP';
// ------------------------------------------------------

var SHEET_HEADERS = [
  'Timestamp', 'Code', 'Full Name', 'Phone', 'Email', 'Country',
  'Check-in', 'Check-out', 'Nights', 'Room Type', 'Price / Night',
  'Total', 'Guests', 'Message', 'Source', 'Status',
  'Gold Card', 'RC PDF'
];

/** Entry point: called automatically whenever a website form is submitted. */
function doPost(e) {
  var lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    var data = parseIncoming(e);
    var sheet = getBookingSheet();

    var rowNumber = sheet.getLastRow() + 1;
    // Prefer the code the guest already saw on screen (from /rc/), so every
    // copy of the reference — screen, sheet, PDF — matches exactly.
    var code = (data.rcCode && String(data.rcCode).trim()) ||
               ('CLM-' + Utilities.formatString('%05d', rowNumber - 1));
    var timestamp = new Date();

    sheet.appendRow([
      timestamp,
      code,
      data.name || '',
      data.phone || '',
      data.email || '',
      data.country || '',
      data.checkin || '',
      data.checkout || '',
      data.nights || '',
      data.room || '',
      data.roomPrice || '',
      data.total || '',
      data.guests || '',
      data.message || '',
      data.source || 'Website',
      'New',
      '', // Gold Card link filled in below
      ''  // RC PDF link filled in below
    ]);

    // Build both PDFs — same booking code on each.
    var cardUrl = buildGoldCard(code, data, timestamp);
    var goldCardCell = sheet.getRange(rowNumber, SHEET_HEADERS.indexOf('Gold Card') + 1);
    if (cardUrl) {
      goldCardCell.setFormula('=HYPERLINK("' + cardUrl + '","Open Gold Card")');
    } else {
      goldCardCell.setValue('Could not generate — open manually');
    }

    var rcUrl = buildReservationCard(code, data, timestamp);
    var rcCell = sheet.getRange(rowNumber, SHEET_HEADERS.indexOf('RC PDF') + 1);
    if (rcUrl) {
      rcCell.setFormula('=HYPERLINK("' + rcUrl + '","Open RC PDF")');
    } else {
      rcCell.setValue('Could not generate — open manually');
    }

    notifyOwner(data, code, cardUrl, rcUrl, timestamp);

    return jsonOutput({ status: 'ok', code: code });
  } catch (err) {
    return jsonOutput({ status: 'error', message: String(err) });
  } finally {
    lock.releaseLock();
  }
}

/** Visiting the deployed URL directly just confirms the service is alive. */
function doGet(e) {
  return ContentService.createTextOutput(
    'CALMA Hotel booking service is running. Bookings are received via POST from the website.'
  );
}

// ---------------------- helpers ----------------------

function parseIncoming(e) {
  // Website sends JSON as text/plain to avoid CORS preflight issues.
  if (e && e.postData && e.postData.contents) {
    try { return JSON.parse(e.postData.contents); } catch (err) { /* fall through */ }
  }
  // Fallback: classic form-encoded POST.
  return (e && e.parameter) ? e.parameter : {};
}

function getBookingSheet() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(SHEET_NAME);
  if (!sheet) {
    sheet = ss.insertSheet(SHEET_NAME);
  }
  if (sheet.getLastRow() === 0) {
    sheet.appendRow(SHEET_HEADERS);
    sheet.getRange(1, 1, 1, SHEET_HEADERS.length).setFontWeight('bold');
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function getDriveFolder(name) {
  var folders = DriveApp.getFoldersByName(name);
  return folders.hasNext() ? folders.next() : DriveApp.createFolder(name);
}

function notifyOwner(data, code, cardUrl, rcUrl, timestamp) {
  var subject = 'New Direct Booking — ' + HOTEL_NAME + ' (' + code + ')';
  var lines = [
    'A new booking/enquiry just came in from the website.',
    '',
    'Code: ' + code,
    'Name: ' + (data.name || '-'),
    'Phone: ' + (data.phone || '-'),
    'Email: ' + (data.email || '-'),
    'Country: ' + (data.country || '-'),
    'Check-in: ' + (data.checkin || '-'),
    'Check-out: ' + (data.checkout || '-'),
    'Nights: ' + (data.nights || '-'),
    'Room: ' + (data.room || '-'),
    'Price / Night: ' + (data.roomPrice ? (data.roomPrice + ' ' + CURRENCY) : '-'),
    'Total: ' + (data.total ? (data.total + ' ' + CURRENCY) : '-'),
    'Guests: ' + (data.guests || '-'),
    'Message: ' + (data.message || '-'),
    'Source: ' + (data.source || 'Website'),
    'Received: ' + timestamp,
    '',
    rcUrl ? ('Reservation Card (RC) PDF: ' + rcUrl) : 'RC PDF could not be generated automatically.',
    cardUrl ? ('Gold Card (15% voucher) PDF: ' + cardUrl) : 'Gold Card could not be generated automatically.',
    '',
    'Full record: ' + SpreadsheetApp.getActiveSpreadsheet().getUrl()
  ];
  MailApp.sendEmail(OWNER_EMAIL, subject, lines.join('\n'));
}

function jsonOutput(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

/** Short, non-legal "verification hash" so the RC PDF can carry a digital
 *  verification stamp tied uniquely to this exact booking (code + guest +
 *  timestamp). Not a cryptographic e-signature — just a tamper-evident stamp. */
function verificationHash(code, data, timestamp) {
  var raw = code + '|' + (data.name || '') + '|' + (data.email || '') + '|' + timestamp.getTime();
  var digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, raw);
  var hex = digest.map(function (b) { return ('0' + (b & 0xFF).toString(16)).slice(-2); }).join('');
  return hex.slice(0, 12).toUpperCase();
}

/**
 * Builds the "Reservation Card" (RC) PDF for one booking — the same summary
 * card design and the same code the guest saw on screen at /rc/, plus a
 * "Digitally Verified" signature stamp. Returns a shareable Drive URL.
 */
function buildReservationCard(code, data, timestamp) {
  var doc, docFile;
  try {
    doc = DocumentApp.create(HOTEL_NAME + ' RC — ' + code);
    var body = doc.getBody();
    body.setMarginTop(0).setMarginBottom(0).setMarginLeft(0).setMarginRight(0);
    body.setPageWidth(580).setPageHeight(430);

    var GOLD = '#B58A45';
    var GOLD_LIGHT = '#D8A85E';
    var ESPRESSO = '#241B12';
    var IVORY = '#F6F1E7';
    var STONE = '#EDE6D8';

    var table = body.appendTable([['']]);
    table.setBorderWidth(2);
    table.setBorderColor(GOLD);
    var cell = table.getCell(0, 0);
    cell.setBackgroundColor(ESPRESSO);
    cell.setPaddingTop(28).setPaddingBottom(24).setPaddingLeft(36).setPaddingRight(36);
    cell.getChild(0).asParagraph().setText('');

    function line(container, text, opts) {
      opts = opts || {};
      var p = container.appendParagraph(text);
      p.setAlignment(opts.align || DocumentApp.HorizontalAlignment.LEFT);
      p.editAsText()
        .setForegroundColor(opts.color || IVORY)
        .setBold(!!opts.bold)
        .setItalic(!!opts.italic)
        .setFontSize(opts.size || 11)
        .setFontFamily('Georgia');
      p.setSpacingAfter(opts.spacingAfter != null ? opts.spacingAfter : 4);
      return p;
    }

    line(cell, 'CALMA HOTEL', { color: GOLD_LIGHT, bold: true, size: 20, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 0 });
    line(cell, 'R E S E R V A T I O N   C A R D', { color: GOLD, bold: true, size: 10.5, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 18 });

    // Two-column details table: labels in gold, values in ivory.
    var rows = [
      ['Reservation Code', code],
      ['Guest', data.name || '-'],
      ['Phone', data.phone || '-'],
      ['Email', data.email || '-'],
      ['Room', data.room || '-'],
      ['Check-in', data.checkin || '-'],
      ['Check-out', data.checkout || '-'],
      ['Nights', data.nights || '-'],
      ['Guests', data.guests || '-']
    ];
    var infoTable = cell.appendTable(rows);
    infoTable.setBorderWidth(0);
    for (var r = 0; r < rows.length; r++) {
      var labelCell = infoTable.getCell(r, 0);
      var valueCell = infoTable.getCell(r, 1);
      labelCell.setPaddingTop(3).setPaddingBottom(3).setWidth(150);
      valueCell.setPaddingTop(3).setPaddingBottom(3);
      labelCell.getChild(0).asParagraph().editAsText().setForegroundColor(GOLD).setFontSize(9.5).setFontFamily('Georgia');
      valueCell.getChild(0).asParagraph().editAsText().setForegroundColor(IVORY).setBold(true).setFontSize(11).setFontFamily('Georgia');
    }

    // Price breakdown banner.
    var priceTable = cell.appendTable([['']]);
    priceTable.setBorderWidth(1);
    priceTable.setBorderColor(GOLD);
    var pCell = priceTable.getCell(0, 0);
    pCell.setBackgroundColor(GOLD);
    pCell.setPaddingTop(10).setPaddingBottom(10).setPaddingLeft(14).setPaddingRight(14);
    pCell.getChild(0).asParagraph().setText('');
    var priceLine = (data.roomPrice ? (data.roomPrice + ' ' + CURRENCY + ' / night') : '-') +
      '   ×   ' + (data.nights || '-') + ' night(s)   =   ' +
      (data.total ? (data.total + ' ' + CURRENCY) : '-') + ' total';
    line(pCell, priceLine, { color: ESPRESSO, bold: true, size: 13, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 2 });
    line(pCell, 'Pay at the property · No prepayment needed', { color: ESPRESSO, size: 9, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 0 });

    // Digital verification / signature stamp.
    var stampTable = cell.appendTable([['']]);
    stampTable.setBorderWidth(1);
    stampTable.setBorderColor(GOLD_LIGHT);
    var sCell = stampTable.getCell(0, 0);
    sCell.setBackgroundColor(ESPRESSO);
    sCell.setPaddingTop(10).setPaddingBottom(10).setPaddingLeft(14).setPaddingRight(14);
    sCell.getChild(0).asParagraph().setText('');
    line(sCell, '✓ Digitally Verified', { color: GOLD_LIGHT, bold: true, italic: true, size: 13, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 2 });
    line(sCell, 'Verification code ' + verificationHash(code, data, timestamp) + '   ·   Issued ' + Utilities.formatDate(timestamp, Session.getScriptTimeZone() || 'GMT+2', 'dd MMM yyyy, HH:mm'), { color: STONE, size: 8.5, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 0 });

    var footer = cell.appendParagraph(HOTEL_NAME + '   ·   ' + HOTEL_PHONE);
    footer.setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    footer.setSpacingBefore(14);
    footer.editAsText().setForegroundColor(GOLD).setFontSize(8).setFontFamily('Georgia');

    doc.saveAndClose();

    docFile = DriveApp.getFileById(doc.getId());
    var pdfBlob = docFile.getAs('application/pdf').setName(HOTEL_NAME + ' RC - ' + code + '.pdf');

    var folder = getDriveFolder(RC_FOLDER);
    var pdfFile = folder.createFile(pdfBlob);
    pdfFile.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);

    docFile.setTrashed(true);

    return pdfFile.getUrl();
  } catch (err) {
    if (docFile) { try { docFile.setTrashed(true); } catch (e2) {} }
    Logger.log('RC PDF generation failed: ' + err);
    return null;
  }
}

/**
 * Builds a "Gold Card" PDF for one booking: guest name, booking code,
 * stay details and a 15% voucher. Returns a shareable Drive URL.
 */
function buildGoldCard(code, data, timestamp) {
  var doc, docFile;
  try {
    doc = DocumentApp.create(HOTEL_NAME + ' Gold Card — ' + code);
    var body = doc.getBody();
    body.setMarginTop(0).setMarginBottom(0).setMarginLeft(0).setMarginRight(0);
    body.setPageWidth(560).setPageHeight(340);

    var GOLD = '#B58A45';
    var GOLD_LIGHT = '#D8A85E';
    var ESPRESSO = '#241B12';
    var IVORY = '#F6F1E7';

    // Outer single-cell "card" table gives us a full-bleed dark background + gold border.
    var table = body.appendTable([['']]);
    table.setBorderWidth(2);
    table.setBorderColor(GOLD);
    var cell = table.getCell(0, 0);
    cell.setBackgroundColor(ESPRESSO);
    cell.setPaddingTop(26).setPaddingBottom(26).setPaddingLeft(34).setPaddingRight(34);

    // Clear the default empty paragraph Docs adds to the cell.
    cell.getChild(0).asParagraph().setText('');

    function line(text, opts) {
      opts = opts || {};
      var p = cell.appendParagraph(text);
      p.setAlignment(opts.align || DocumentApp.HorizontalAlignment.LEFT);
      p.editAsText()
        .setForegroundColor(opts.color || IVORY)
        .setBold(!!opts.bold)
        .setFontSize(opts.size || 11)
        .setFontFamily('Georgia');
      p.setSpacingAfter(opts.spacingAfter != null ? opts.spacingAfter : 4);
      return p;
    }

    line('CALMA HOTEL', { color: GOLD_LIGHT, bold: true, size: 22, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 0 });
    line('G O L D   C A R D', { color: GOLD, bold: true, size: 11, align: DocumentApp.HorizontalAlignment.CENTER, spacingAfter: 16 });

    line('Guest', { color: GOLD, size: 9, spacingAfter: 0 });
    line(data.name || '-', { color: IVORY, bold: true, size: 15, spacingAfter: 10 });

    line('Booking Code', { color: GOLD, size: 9, spacingAfter: 0 });
    line(code, { color: IVORY, bold: true, size: 15, spacingAfter: 10 });

    var stayDetails = 'Room: ' + (data.room || '-') +
      '   |   Check-in: ' + (data.checkin || '-') +
      '   |   Check-out: ' + (data.checkout || '-') +
      '   |   Guests: ' + (data.guests || '-');
    line(stayDetails, { color: IVORY, size: 10.5, spacingAfter: 18 });

    // Voucher banner
    var voucherTable = cell.appendTable([['']]);
    voucherTable.setBorderWidth(1);
    voucherTable.setBorderColor(GOLD);
    var vCell = voucherTable.getCell(0, 0);
    vCell.setBackgroundColor(GOLD);
    vCell.setPaddingTop(10).setPaddingBottom(10).setPaddingLeft(14).setPaddingRight(14);
    vCell.getChild(0).asParagraph().setText('');
    var vp1 = vCell.appendParagraph(VOUCHER_PCT + ' OFF YOUR NEXT STAY');
    vp1.setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    vp1.editAsText().setForegroundColor(ESPRESSO).setBold(true).setFontSize(14).setFontFamily('Georgia');
    var vp2 = vCell.appendParagraph('Present this card and booking code at check-in. One use per stay.');
    vp2.setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    vp2.editAsText().setForegroundColor(ESPRESSO).setFontSize(9).setFontFamily('Georgia');

    var footer = cell.appendParagraph(HOTEL_NAME + '   ·   ' + HOTEL_PHONE + '   ·   Issued ' + Utilities.formatDate(timestamp, Session.getScriptTimeZone() || 'GMT+2', 'dd MMM yyyy'));
    footer.setAlignment(DocumentApp.HorizontalAlignment.CENTER);
    footer.setSpacingBefore(16);
    footer.editAsText().setForegroundColor(GOLD).setFontSize(8).setFontFamily('Georgia');

    doc.saveAndClose();

    docFile = DriveApp.getFileById(doc.getId());
    var pdfBlob = docFile.getAs('application/pdf').setName(HOTEL_NAME + ' Gold Card - ' + code + '.pdf');

    var folder = getDriveFolder(DRIVE_FOLDER);
    var pdfFile = folder.createFile(pdfBlob);
    pdfFile.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);

    // Clean up the intermediate Google Doc — we only need to keep the PDF.
    docFile.setTrashed(true);

    return pdfFile.getUrl();
  } catch (err) {
    if (docFile) { try { docFile.setTrashed(true); } catch (e2) {} }
    Logger.log('Gold Card generation failed: ' + err);
    return null;
  }
}
